# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#pod 'SideMenu'

pod 'MBProgressHUD'
# add the Firebase pod for Google Analytics
# add pods for any other desired Firebase products

target 'UHFSample' do
  
end

